### ISSUE TITLE
Docker terminal tag doesn't work

### ISSUE THREAD

**Issue by panManfredini** [XENON1T/Xephyr#29]
```bash
sudo docker run --rm yossimo/xephyr:terminal

root: can't figure out DISPLAY, set it manually
In case you run a remote ssh session, restart your ssh session with:
=========>  ssh -Y

```

**Comment by panManfredini** [comment]
I got a bit more displayed stuff by adding:
``` 
export DISPLAY=localhost:0.0
```
before the ENTRYPOINT

but no luck so far.... Anyway docker is not really meant for interactive terminal...

Would be cool if this would simply run the compiler on your code and link all libs in a mounted volume. So just provide your code compiled (somehow)... Anyway xephyr was not really designed to be used interactively (except for a few plotting feature).

Ciao :)

**Comment by jmosbacher** [comment]
Thanks for noticing this, I was running the notebook version when testing. You can share your local X11 display with the docker container if you want display stuff to work like the TBrowser:
docker run -it -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$DISPLAY yossimo/xephyr:terminal
otherwise you need to run root in batch mode.

**Comment by jmosbacher** [comment]
Closing this since its an issue with root in docker and not Xephyr. README was updated to run the image with the local X11 display mounted to the docker instance.
